server:
  port: 8080
  servlet:
    context-path: /sell
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://35.220.171.186:3306/sell?useSSL=false
    username: root
    password: "@Chenjiewen1996"
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true
    initialSize: 1
    minIdle: 3
    maxActive: 30
    maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 30000


mybatis:
  #实体类所做包
  type-aliases-package: com.chenjiewen.wxsell.model
  #mapper.xml所在位置
  mapper-locations: classpath:mapping/*.xml
  #开启驼峰转换
  configuration:
    map-underscore-to-camel-case: true

wechat:
  mpAppId: wxef9ffe8df044941e
  mpAppSecret: 8608baea6b73936076e3dd61684fca97

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql