server:
  port: 8080
  servlet:
    context-path: /sell
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sell?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: "chenjiewen"
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true
    initialSize: 1
    minIdle: 3
    maxActive: 30
    maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 30000
  redis:
    host: 35.220.208.164
    port: 6379
    password: chenjiewen

file.staticAccessPath: /api/file/**

file.uploadFolder: /Users/chenjiewen/upload/


mybatis:
  #实体类所做包
  type-aliases-package: com.chenjiewen.wxsell.model
  #mapper.xml所在位置
  mapper-locations: classpath:mapping/*.xml
  #开启驼峰转换
  configuration:
    map-underscore-to-camel-case: true

wechat:
  mpAppId: wxef9ffe8df044941e
  mpAppSecret: 8608baea6b73936076e3dd61684fca97



pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

messages:
  AppID: 73191c66cd9a4d95a92ae66456331872
  AccountSid: 82b123cdf4450c6aa77b6cbe6fe3e1c2
  AuthToken: a04b1a493f9c8a7816d67deb702f5095
  RestURL: https://open.ucpaas.com/ol/sms/{function}
  SuccessTp: 465909
  FailTp: 465914
  Code: 465913


orc:
  clientId: g869eR9FlHHmT1mjztMSHGRI
  clientSecret: DlLGU3q8VLjYqvw9GYUnEkePPMFXnh0e